# Generated by Django 4.2 on 2024-04-24 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(blank=True, choices=[('admin', 'Full access'), ('moscow', 'Head office: Moscow'), ('ulyanonsk', 'Ulyanovsk branch')], max_length=32, null=True, verbose_name='Место деятельности')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджера',
                'verbose_name_plural': 'Менеджеров',
            },
        ),
    ]
