# Generated by Django 4.2 on 2024-06-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Менеджера', 'verbose_name_plural': 'Менеджеры'},
        ),
    ]
