# Generated by Django 4.2 on 2023-07-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('ДА', 'ПЕРЕЗВОНИЛИ'), ('НЕТ', 'НЕ ПЕРЕЗВОНИЛИ')], default='НЕТ', max_length=3)),
                ('date_application', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_application'],
            },
        ),
    ]
