# Generated by Django 4.2 on 2023-07-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
