# Generated by Django 4.2 on 2023-07-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_consultation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('want_to', models.CharField(choices=[('не выбран', 'не выбран'), ('практика', 'прохождение практики'), ('стажер', 'стажировка'), ('юр.помощник', 'помощник юриста'), ('юрист', 'юрист'), ('адвокат', 'адвокат')], default='не выбран', max_length=30)),
                ('education', models.CharField(max_length=100)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('mail', models.CharField(max_length=100)),
                ('covering', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='')),
                ('agree', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('не выбран', 'не выбран'), ('практика', 'прохождение практики'), ('стажер', 'стажировка'), ('юр.помощник', 'помощник юриста'), ('юрист', 'юрист'), ('адвокат', 'адвокат')], default='НЕТ', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
